language: c
sudo: true
git:
  submodules: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - cmake
install:
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
        sudo apt-get update;
        apt-cache search icd;
        apt-cache search opencl;
        apt-cache search pocl;
        sudo apt-get install -y ocl-icd-opencl-dev;
    fi
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar xf cmocka-1.0.1.tar.xz
  - cd cmocka-1.0.1 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .. && make && sudo make install
compiler:
    - clang
    - gcc
script: cd $TRAVIS_BUILD_DIR &&  make
