language: node_js
sudo: false
node_js:
- 4.2.4
script: npm test
addons:
  apt:
    packages:
    - sshpass
after_success:
- cat travtest_rsa.pub
env:
  global:
before_install:
- openssl aes-256-cbc -K $encrypted_c9cd749dbd63_key -iv $encrypted_c9cd749dbd63_iv
  -in travtest_rsa.pub.enc -out ./travtest_rsa.pub -d
