language: node_js
sudo: false
node_js:
  - 4.2.4
script: npm test
addons:
  apt:
    packages:
      - sshpass
after_success:
  - export SSHPASS=$DEPLOY_DEV_PASS
  - sshpass -e ssh $DEPLOY_DEV_USER@$DEPLOY_DEV_HOST "git -C ${DEPLOY_DEV_PATH} pull"
  - sshpass -e ssh $DEPLOY_DEV_USER@$DEPLOY_DEV_HOST $DEPLOY_DEV_PATH/deploy-dev.sh
