language: node_js
sudo: false
script: npm test
after_success:
- cat travtest_rsa.pub
- ssh -i travtest_rsa -o StrictHostKeyChecking=no travtest@travtest.memmi.net "touch test"
env:
  global: 
before_install:
- openssl aes-256-cbc -K $encrypted_c9cd749dbd63_key -iv $encrypted_c9cd749dbd63_iv
  -in travtest_rsa.enc -out ./travtest_rsa -d
